version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tradewide
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/tradewide?schema=public
      - JWT_SECRET=supersecure_fallback_key_that_should_be_changed
      - PORT=3000
      - SENDGRID_API_KEY=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
      - SENDGRID_FROM_EMAIL=29adityaprasad@gmail.com
      - db

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  postgres_data:
